name: buildAsciidoc

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: mkdir docs
    - uses: mgred/asciidoctor-action@master
      with:
        args: make
    - run: |
        cd docs
        git init
        git config --local user.name "jamesread" 
        git config --local user.email "contact@jread.com"
        git add . 
        git commit -m "Deploy to GH Pages"
        git push --force --quiet "https://jamesread:${{ secrets.GITHUB_TOKEN }}@github.com/jamesread/openshift4-on-libvirt-tutorial.git" master:gh-pages
