name: buildAsciidoc

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: mkdir docs
    - uses: mgred/asciidoctor-action@master
      with:
        args: asciidoctor index.adoc -b html5 -D docs/
        
